---

- name: "Create Host Objects"
  sns_command:
    appliance: "{{ hostvars[inventory_hostname].appliance }}"
    force_modify: "{{ hostvars[inventory_hostname].force_modify | default(false) }}"
    command: CONFIG OBJECT HOST NEW name="{{ item.name }}" ip="{{ item.ip }}" type=host comment="{{ item.comment }}" update=1
  with_items: "{{ Hosts }}"

- name: "Create Network Objects"
  sns_command:
    appliance: "{{ hostvars[inventory_hostname].appliance }}"
    force_modify: "{{ hostvars[inventory_hostname].force_modify | default(false) }}"
    command: CONFIG OBJECT NETWORK NEW name="{{ item.name }}" ip="{{ item.ip }}" mask="{{ item.mask }}" comment="{{ item.comment }}" update=1
  with_items: "{{ Networks }}"

- name: "Validation des modifications"
  sns_command:
    appliance: "{{ hostvars[inventory_hostname].appliance }}"
    force_modify: "{{ hostvars[inventory_hostname].force_modify | default(false) }}"
    command: CONFIG OBJECT ACTIVATE
