name: Pylint

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=9 $(git ls-files '*.py') > pylint.log
      - name: Generate badge
        run: |
          SCORE=$(pylint Modules/Stormshield/next_hop_calculator.py --exit-zero | grep "Your code has been rated at" | awk '{print $7}' | cut -d/ -f1)
          COLOR="brightgreen"
          mkdir -p docs
          echo "{\"schemaVersion\":1,\"label\":\"pylint\",\"message\":\"$SCORE/10\",\"color\":\"$COLOR\"}" > docs/pylint.json
      - name: Commit badge JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/pylint.json
          git commit -m "Update pylint badge [skip ci]" || echo "No changes"
          git push
